export default {
    template: [],
    cart: [],
    buyer: [],
    orders: [],
    products: [
    {
    "isbn": "9781593279509",
    "title": "Eloquent JavaScript, Third Edition",
    "subtitle": "A Modern Introduction to Programming",
    "author": "Marijn Haverbeke",
    "published": "2018-12-04T00:00:00.000Z",
    "publisher": "No Starch Press",
    "pages": 472,
    "description": "JavaScript lies at the heart of almost every modern web application",
    "price": 120,
    "image": "https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson.jpg",
    "coutas" : "3 cuotas sin interes"
    },
    {
    "isbn": "9781491943533",
    "title": "Practical Modern JavaScript",
    "subtitle": "Dive into ES6 and the Future of JavaScript",
    "author": "Nicolás Bevacqua",
    "published": "2017-07-16T00:00:00.000Z",
    "publisher": "O'Reilly Media",
    "pages": 334,
    "description": "To get the most out of modern JavaScript,",
    "price": 120,
    "image": "https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson.jpg",
    "coutas" : "3 cuotas sin interes"
    },
    {
    "isbn": "9781593277574",
    "title": "Understanding ECMAScript 6",
    "subtitle": "The Definitive Guide for JavaScript Developers",
    "author": "Nicholas C. Zakas",
    "published": "2016-09-03T00:00:00.000Z",
    "publisher": "No Starch Press",
    "pages": 352,
    "description": "ECMAScript 6 represents the biggest update to the core of JavaScript in the history of the language.",
    "price": 120,
    "image": "https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson.jpg",
    "coutas" : "3 cuotas sin interes"
    },
    {
    "isbn": "9781449365035",
    "title": "Speaking JavaScript",
    "subtitle": "An In-Depth Guide for Programmers",
    "author": "Axel Rauschmayer",
    "published": "2014-04-08T00:00:00.000Z",
    "publisher": "O'Reilly Media",
    "pages": 460,
    "description": "Like it or not, JavaScript is everywhere these days ",
    "price": 120,
    "image": "https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson.jpg",
    "coutas" : "3 cuotas sin interes"    },
    {
    "isbn": "9781449331818",
    "title": "Learning JavaScript Design Patterns",
    "subtitle": "A JavaScript and jQuery Developer's Guide",
    "author": "Addy Osmani",
    "published": "2012-08-30T00:00:00.000Z",
    "publisher": "O'Reilly Media",
    "pages": 254,
    "description": "With Learning JavaScript Design Patterns, you'll learn how to write beautiful.",
    "price": 120,
    "image": "https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson.jpg",
    "coutas" : "3 cuotas sin interes"    },
    {
    "isbn": "9798602477429",
    "title": "You Don't Know JS Yet",
    "subtitle": "Get Started",
    "author": "Kyle Simpson",
    "published": "2020-01-28T00:00:00.000Z",
    "publisher": "Independently published",
    "pages": 143,
    "description": "The worldwide best selling You Don't Know JS ",
    "price": 120,
    "image": "https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson.jpg",
    "coutas" : "3 cuotas sin interes"    },
    {
    "isbn": "9781484200766",
    "title": "Pro Git",
    "subtitle": "Everything you neeed to know about Git",
    "author": "Scott Chacon and Ben Straub",
    "published": "2014-11-18T00:00:00.000Z",
    "publisher": "Apress; 2nd edition",
    "pages": 458,
    "description": "Pro Git (Second Edition) is your fully-updated guide ",
    "price": 120,
    "image": "https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson.jpg",
    "coutas" : "3 cuotas sin interes"    },
    {
    "isbn": "9781484242216",
    "title": "Rethinking Productivity in Software Engineering",
    "subtitle": "",
    "author": "Caitlin Sadowski, Thomas Zimmermann",
    "published": "2019-05-11T00:00:00.000Z",
    "publisher": "Apress",
    "pages": 310,
    "description": "Get the most out of this foundational reference and improve ",
    "price": 120,
    "image": "https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson.jpg",
    "coutas" : "3 cuotas sin interes"    },
  ],
};